version: '3.9'

services:
  db:
    container_name: postgres.players.dev
    image: postgres:latest
    env_file: .env
    environment:
      POSTGRES_DB: $DATABASE_NAME
      POSTGRES_USER: $DATABASE_USERNAME
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
    volumes:
      - postgres_players_data:/data/postgres
    ports:
      - 5432:5432
    networks:
      - players_network
  app:
    container_name: app.players.dev
    env_file: .env
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/app
    ports:
      - 9000:9000
    depends_on:
      - db
    networks:
      - players_network

volumes:
  postgres_players_data:

networks:
  players_network:
